# Generated by Django 4.0.3 on 2022-04-04 13:58

import contacts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=255, verbose_name='lastname')),
                ('phone_number', contacts.validators.PhoneValidator(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+98**********'. Up to 11 digits allowed.", regex='^(\\+98|0)?9\\d{9}$')])),
                ('slug_field', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-created_date'],
            },
        ),
    ]
