# Generated by Django 4.0.3 on 2022-04-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
