# Generated by Django 4.0.3 on 2022-04-04 14:37

import contacts.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_slug_field_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_phone',
            field=contacts.validators.HomePhone(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+98**********'. Up to 11 digits allowed.", regex='^(\\+98|0)\\d{10}$')]),
        ),
    ]
